### ISSUE TITLE
Add ProGuard/R8 rules in the readme

### ISSUE THREAD

**Issue by adamszewe** [Adyen/adyen-3ds2-android#12]
While testing the 3DS2 transactions with the ProcessOut sdk and Adyen's 3DS2 Handler we experienced issues with fingerprinting.

The transaction would stop at the fingerprinting state because fingerprinting would fail because of issues caused by obfuscation. 
Using a non-obfuscated build type or disabling obfuscation works and the transactions are authorised as expected - but using Proguard/R8 to obfuscate the build changes some of the Adyen's files and in production fingerprinting fails.

I used the following ProGuard/R8 rule: 
```
-keep class com.adyen.threeds2.** { *; }
```

You could add this to your readme to make the documentation complete.

**Comment by timon-langlotz** [comment]
Hi @adamszewe,

Thanks for your feedback! We'll include that for the next release.

Cheers,
Timon

**Comment by timon-langlotz** [comment]
Hi @adamszewe,

we've added consumer Proguard rules in our latest [release](https://github.com/Adyen/adyen-3ds2-android/releases/tag/2.1.0-rc05), so you shouldn't need to specify these rules manually anymore.

Cheers,
Timon
