### ISSUE TITLE
Must not be called on the main application thread

### ISSUE THREAD

**Issue by jnorkus** [Adyen/adyen-3ds2-android#16]
On Android 10 (works fine on Android 9) a call to`ThreeDS2Service.INSTANCE.initialize` results in the following exception:

![image](https://user-images.githubusercontent.com/5137138/69037268-3d17ea80-09f0-11ea-8f99-2d979535260f.png)

**Comment by timon-langlotz** [comment]
Hi @jnorkus,

`initialize(Context, ConfigParameters, String, UiCustomization)` should be called from a background thread. The documentation of the method indicates that, but it's unfortunately not 100% clear:
> Depending on the App's implementation, a ThreeDS2Service instance initialization shall be called either during the App startup **as a background task** or when a transaction is initiated.

We'll update the documentation to make this clear.

Regards,
Timon
