### ISSUE TITLE
launchMode="singleTask" 

### ISSUE THREAD

**Issue by shchurov** [Adyen/adyen-3ds2-android#17]
Our main activity has `android:launchMode="singleTask"` in its declaration in manifest. 
Steps to reproduce the issue:
- Start 3ds2 challenge (opens Challenge Activity)
- Put the app to background
- Run the app from launcher icon

As a result Challenge Activity is being closed without calling any methods of ChallengeStatusReceiver. Because of that the original activity can't know if the challenge is still in progress.

**Comment by caiofaustino** [comment]
Hey,
So the `Transaction` object always needs to be saved to continue the flow. In case of Activity being destroyed, currently the only way to save it is to put it in a static variable.

We know this is not ideal on Android, and we are working on refactoring this to probably make the object parcelable, but we don't currently have an ETA for that.

**Comment by shchurov** [comment]
Hey @caiofaustino .
Per my understanding the issue is not related to the way how `Transaction` is being stored.
Basically,  launchMode="singleTask" means that if user tries to launch an app that is already running, the system will resume it and pop all the activites that are started on top of the "launcher" activity.
What happens in the case I described:
- User resumes the app by clicking launcher icon 
- System sees that ChallengeActivity is running on top of my MainActivity (the "launcher" one) and destroys it.
- MainActivity is still waiting for ChallengeActivity to invoke a method from ChallengeStatusReceiver.

I'm quite sure that the system invokes `onDestroy` method of ChallengeActivity so it can be overriden and call `cancelled()` method of ChallengeStatusReceiver if such situation happens.

**Comment by caiofaustino** [comment]
Ah yeah, I see what you mean, sorry I misunderstood the issue before. We'll investigate this.

**Comment by sewerk** [comment]
Hey, do you have a solution or recommendation for this case?
