### ISSUE TITLE
Custom ContextWrapper compatibility

### ISSUE THREAD

**Issue by shchurov** [Adyen/adyen-3ds2-android#19]
I'm getting an exception when trying to use a custom ContextWrapper in my app.
```
java.lang.RuntimeException: Unable to instantiate receiver com.adyen.threeds2.internal.AppUpgradeBroadcastReceiver: java.lang.ClassCastException: com.wolt.android.WoltApp$CustomWrapper cannot be cast to android.app.ContextImpl
```

**Comment by caiofaustino** [comment]
Can you share a bit more information on how you are using the ContextWrapper?

**Comment by shchurov** [comment]
I'm overriding `fun attachBaseContext(base: Context?)` in my Application class and wrapping the base context inside my custom wrapper. I'm using it in order to customize the LayoutInflater similar to what this library is does https://github.com/chrisjenx/Calligraphy. 
I might be wrong but I think you need to get the original context by calling recursively `getBaseContext()`. And only then instantiate the BroadcastReceiver using this context.

**Comment by caiofaustino** [comment]
That `BroadcastReceiver` is not instantiated directly, it's only declared on the XML. I can't find a usage of the Context that would cause that specific issue on our end. Do you have a full stacktrace that maybe has more information? Does your custom `ContextWrapper` extend the [Android one](https://developer.android.com/reference/android/content/ContextWrapper)?

**Comment by shchurov** [comment]
I'm able to reproduce the crash by putting this inside my Application class:
```
    override fun attachBaseContext(newBase: Context) {
        super.attachBaseContext(ContextWrapper(newBase))
    }
```

Here's the full stacktrace:
```
java.lang.RuntimeException: Unable to instantiate receiver com.adyen.threeds2.internal.AppUpgradeBroadcastReceiver: java.lang.ClassCastException: android.content.ContextWrapper cannot be cast to android.app.ContextImpl
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3774)
        at android.app.ActivityThread.access$1400(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1870)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by caiofaustino** [comment]
From a quick search here it seems to me that you misunderstood the use of the library a bit.
From what I saw [here](https://github.com/chrisjenx/Calligraphy#inject-into-context) they intend you to call `attachBaseContext` on the `Activity` and not in the `Application` class.

Looking at the stacktrace I track down the code on the [framework](http://androidxref.com/9.0.0_r3/xref/frameworks/base/core/java/android/app/ActivityThread.java#3349) and it seems to me that the BaseContext of the Application should not be a ContextWrapper.

I'll try to do some more tests here, but it seems to me that the same would happen to any BroadcastReceiver you declare in your XML, and even some other scenarios.

Let me know if there is anything else I'm missing here.

**Comment by shchurov** [comment]
In this specific case I need to modify app-context LayoutInflater to intercept creation of overlay views that are displayed outside of an Activity window.
But I think you're right, looking at the framework code it seems to have a bug. So not much you can do here. Anyway, thanks for the quick reply! 👍
