### ISSUE TITLE
SDK seems to load directory server id from resources and ignores the parameter sent in createTransaction()

### ISSUE THREAD

**Issue by Ajibola** [Adyen/adyen-3ds2-android#2]
I kept getting an InvalidInputException while calling service.createTransaction(_, _), it appears the SDK is trying to fetch a raw json resource instead of using the parameters passed in.

It is not clear from the docs that ConfigParameters setup during initialise() of service can be used to override the parameters for createTransaction if "paymentSystemId" is null or empty.

**Comment by ran-haveshush** [comment]
Hi @Ajibola,

Thanks for the feedback, in the latest version 0.9.2 we have added inline JavaDoc I hope it will clear the API. Can you check if the issue persists in the latest version?

**Comment by ran-haveshush** [comment]
@Ajibola are you still experiencing this issue in the latest version?

**Comment by Ajibola** [comment]
@ran-haveshush this issue is resolved in latest version
