### ISSUE TITLE
IllegalStateException: Must not be called on the main application thread

### ISSUE THREAD

**Issue by shchurov** [Adyen/adyen-3ds2-android#20]
We're receiving quite many automatic reports in Crashlytics with this stacktrace:
```
Non-fatal Exception: java.lang.IllegalStateException: Must not be called on the main application thread
       at com.google.android.gms.common.internal.Preconditions.checkNotMainThread(Preconditions.java:51)
       at com.google.android.gms.common.internal.Preconditions.checkNotMainThread(Preconditions.java:48)
       at com.google.android.gms.tasks.Tasks.await(Tasks.java:24)
       at atd.m.f$b.a(f.java:151)
       at atd.m.f.a(f.java:59)
       at atd.m.f$d.c(f.java:104)
       at atd.m.f$d.b(f.java:91)
       at atd.i.d.a(d.java:40)
       at atd.h.b.a(b.java:101)
       at atd.h.b.<init>(b.java:60)
       at atd.h.b.a(b.java:51)
       at com.adyen.threeds2.internal.g.initialize(g.java:93)
```

According to the logs, it happens when the app calls `AdyenConfigParameters.Builder(serverId, publicKey).build()`. We can't reproduce it in our tests.
Although I can't find any information on threading in the SDK docs, we always operate with the SDK on the main thread.

Devices: different models from Samsung, Huawei, Xiaomi, Oneplus, and others.
SDK version: 2.1.0-rc08

**Comment by caiofaustino** [comment]
hey Mike,

The `ThreeDS2Service.initialize()` should be called in a background thread. We have a note about that in the documentation of the method but I'll try to make it cleared in the readme as well.

Can you please check if that solve the issue for you?

**Comment by shchurov** [comment]
Hey @caiofaustino,
Thanks for the reply! Can you confirm that I should call this whole block for creating a transaction (https://github.com/Adyen/adyen-3ds2-android#creating-a-transaction) in a background thread? What about `transaction.doChallenge`?

**Comment by caiofaustino** [comment]
The `initialize` call is the only one that I'm aware that is required to be called in a background thread because of some checks that might be required, but it's also fine to call the whole block there. 
`doChallenge` will inevitably launch an intent to the challenge activity, I'm not sure if that needs to be done in the main thread or not, my intuition is that is should be OK since [the app is in foreground](https://developer.android.com/guide/components/activities/background-starts), but I'd keep it in the main thread just in case.

**Comment by shchurov** [comment]
Got it, just to confirm, it means that I'll need to pass the transaction object between threads?

**Comment by caiofaustino** [comment]
Not really, you can just reference it in a Runnable to a Handler for example. Here is an [example](https://github.com/Adyen/adyen-android/blob/master/3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Component.java#L198) on how we use it in our Components.

**Comment by shchurov** [comment]
I'm a bit confused. Maybe you can clarify 🙂 
1. In your example, `mTransaction` is assigned inside `ThreadManager.EXECUTOR` (which runs in a background thread I assume): https://github.com/Adyen/adyen-android/blob/master/3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Component.java#L216
2. And then `mTransaction` is used with `doChallenge` (which should be called from the main thread): https://github.com/Adyen/adyen-android/blob/master/3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Component.java#L258

Per my understanding you're using `mTransaction` in multiple threads, aren't you?
Should `mTransaction` be marked as `volatile` then?

**Comment by caiofaustino** [comment]
Yes it's being used in multiple threads, we hadn't considered the need for using `volatile` since the `doChallenge` call happens way later in the flow and doesn't have any possible concurrency issues. But thanks for pointing it out, we'll investigate more and consider adding that if necessary.

**Comment by shchurov** [comment]
Great, thanks for the clarification 👍
