### ISSUE TITLE
Protocol version 2.2.0

### ISSUE THREAD

**Issue by kaserdan** [Adyen/adyen-3ds2-android#22]
Hi,
I am not able to make 3DS2 version 2.2.0 work.
I have followed [migration guide](https://docs.adyen.com/online-payments/classic-integrations/api-integration-ecommerce/3d-secure/native-3ds2/migrating-to-2-2?tab=oob-android_2)
I upgraded to library version 2.2.1 but still can't get the latest protocol version to work, everything works fine with protocol version 2.1.0.

Transaction initialization:
```
val transaction = ThreeDS2Service.INSTANCE.createTransaction(null, null)
```
Challenge parameters:
```
 val challengeParameters = ChallengeParameters()
 challengeParameters.set3DSServerTransactionID(challenge.threeDSServerTransID)
 challengeParameters.acsTransactionID = challenge.acsTransID
 challengeParameters.acsRefNumber = challenge.acsReferenceNumber
 challengeParameters.acsSignedContent = challenge.acsSignedContent
 challengeParameters.threeDSRequestorAppURL = ChallengeParameters.getEmbeddedRequestorAppURL(context)
```

When I try to do challenge with ` transaction.doChallenge(activity, challengeParameters, receiver, challengeTimeOut)` I get following **error**: 
```
Error [code: 203, description: Data element value is invalid, details: messageVersion]
```

If version 2.1.0 is defined via `ThreeDS2Service.INSTANCE.createTransaction(null, "2.1.0")`, everything works without any issue.

Are any changes needed? Do we need to change something on our backend side?

**Comment by caiofaustino** [comment]
Hi there, can you tell us where you get the error from? Setting a wrong protocol version would throw an `InvalidInputException` instead. Do you get this error from the server?

**Comment by kaserdan** [comment]
I get this error in callback `ChallengeStatusReceiver.protocolError(protocolErrorEvent: ProtocolErrorEvent)` which is passed to `transaction.doChallenge(...)` method

ProtocolErrorEvent contains following values:
errorCode: 203
errorDescription: Data element value is invalid
errorDetails: messageVersion
transactionId: 2b33a24a-e05a-4455-b0e3-fb568c6a5f0d

stacktrace:
```
***.Card3DS2Authenticator$ThreeDS2Exception: Error [code: 203, description: Data element value is invalid, details: messageVersion]
***.usecase.Card3DS2Authenticator$presentChallenge$result$1$receiver$1.protocolError(Card3DS2Authenticator.kt:155)
     at com.adyen.threeds2.internal.w.protocolError(:3)
     at com.adyen.threeds2.internal.s.a(:46)
     at com.adyen.threeds2.internal.g.a(:7)
     at com.adyen.threeds2.internal.g.accept(:1)
     at com.adyen.threeds2.internal.s.a(:23)
     at com.adyen.threeds2.internal.s.a(:40)
     at com.adyen.threeds2.internal.s.b(:17)
     at com.adyen.threeds2.internal.s.a(:3)
```

**Comment by kaserdan** [comment]
Ah, it seems that the issue is that version in token is still "2.1.0" so I will keep using messageVersion
