### ISSUE TITLE
Updating library from 2.2.0 to 2.2.1 causes a build error

### ISSUE THREAD

**Issue by korva** [Adyen/adyen-3ds2-android#24]
**Describe the bug**
After updating library version in build.gradle from 2.2.0 to "com.adyen.threeds:adyen-3ds2:2.2.1" I get this error when build the project:

Execution failed for task ':app:dataBindingMergeDependencyArtifactsDevDebug'.
> Could not resolve all files for configuration ':app:devDebugCompileClasspath'.
   > Failed to transform adyen-3ds2-2.2.1.aar (com.adyen.threeds:adyen-3ds2:2.2.1) to match attributes {artifactType=android-databinding, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for JetifyTransform: /Users/jaakko/.gradle/caches/modules-2/files-2.1/com.adyen.threeds/adyen-3ds2/2.2.1/3d50acb5b952df1a6197dbaa279a9e6de7729cf0/adyen-3ds2-2.2.1.aar.
         > Failed to transform '/Users/jaakko/.gradle/caches/modules-2/files-2.1/com.adyen.threeds/adyen-3ds2/2.2.1/3d50acb5b952df1a6197dbaa279a9e6de7729cf0/adyen-3ds2-2.2.1.aar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 59. (Run with --stacktrace for more details.)

"Unsupported class file major version 59" any ideas what causes this?

**Desktop**
 - OS: MacOS 11.1
 - Android Studio 4.1.2

**Comment by caiofaustino** [comment]
Yeah, sorry about that, take a look at #23, looks like the same issue. We updated a dependency that used Java 15 dex code that is not supported by the Jetifier, but we use AndroidX libs so you can exclude the SDK from bein "jettified".

**Comment by caiofaustino** [comment]
This should be fixed in `2.2.2` could you please check?

**Comment by korva** [comment]
Yes, with 2.2.2 the build worked without problems, thanks!
