### ISSUE TITLE
Migrate from JCenter 

### ISSUE THREAD

**Issue by caiofaustino** [Adyen/adyen-3ds2-android#25]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by guilherme-pereira-ifood** [comment]
Hi @caiofaustino. Is there any update on this?

**Comment by caiofaustino** [comment]
We are working on it, I'll keep the issue updated.

**Comment by caiofaustino** [comment]
Version `2.2.2` is fully available from Maven Central and Google repository now. Previous versions have a dependency that has not yet been migrated, but I asked the maintainer to do that as well.
https://github.com/MichaelRocks/paranoid/issues/45

Future version will hopefully not have that dependency anymore.
