### ISSUE TITLE
Documentation not up to date

### ISSUE THREAD

**Issue by korva** [Adyen/adyen-3ds2-android#28]
Using the documentation in readme.md we ran into some issues when trying to do 3DS2 challenges in production. Turned out, there is a more up-to-date documentation (at least for our integration) located in https://docs.adyen.com/online-payments/classic-integrations/api-integration-ecommerce/3d-secure/native-3ds2/android-sdk-integration

Specifically usage of the messageVersion parameter probably caused the errors we saw. Maybe refer to above page here or update the readme?

**Comment by caiofaustino** [comment]
Thanks for pointing this out, we will add a clarification to the Readme file.

**Comment by caiofaustino** [comment]
Fixed in latest release, thx again for the recommendation.
