### ISSUE TITLE
Challenge fail for Revolut payment

### ISSUE THREAD

**Issue by kaserdan** [Adyen/adyen-3ds2-android#31]
**Describe the bug**
I am using Adyen 3DS2 Sdk version 2.2.0 and I keep getting following error while trying to pay with [Revolut](https://www.revolut.com/) payment card:
```
Error [code: 203, description: Data element not in the required format or value is invalid as defined in Table A.1, details: threeDSRequestorAppURL]
```
```
{"messageType":"Erro","messageVersion":"2.1.0","errorCode":"203","errorComponent":"A","errorDescription":"Data element not in the required format or value is invalid as defined in Table A.1","errorDetail":"threeDSRequestorAppURL","errorMessageType":"CReq","threeDSServerTransID":"1c989e42-e9f0-4254-84e2-8fc097c7a6a8","acsTransID":"afd33f92-b47a-44e1-b86b-e5fc22874329","dsTransID":"d258d3d4-fde8-439e-8dc3-2abf1f450933","sdkTransID":"3827d5a8-ebaf-4dd4-ad5b-5cea3150f0f2"}
```

Is there something wrong on issuer part or is in the SDK?

**Comment by caiofaustino** [comment]
Hey, this seems to be an issue sent by the Revolut server.  Do you define this variable in the `ChallengeParameters`?
My understanding is that this is optional, but if you do add it, it should look something like this.
`challengeParameters.setThreeDSRequestorAppURL(ChallengeParameters.getEmbeddedRequestorAppURL(this));`

**Comment by kaserdan** [comment]
It seems to be set properly:
https://github.com/kaserdan/ProguardIssueSample/blob/master/screenshot.png?raw=true

**Comment by kaserdan** [comment]
Ah, I have now tried the oposite - leave it empty. Now it's working ok. 
Is this field realy optional? Even for messageVersion 2.2.0? (right now this is messageVersion 2.1.0)
If so, I will just leave it empty.

**Comment by caiofaustino** [comment]
Ahh good point, so my understanding is that it should not be present in messageVersion `2.1.0` and is optional is `2.2.0`.

**Comment by kaserdan** [comment]
ok, thanks :+1:

**Comment by kaserdan** [comment]
Just to mention, checkout sdk is setting this field without considering messageVersion:
https://github.com/Adyen/adyen-android/blob/develop/3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Component.kt
Maybe it should be fixed?

**Comment by caiofaustino** [comment]
https://github.com/Adyen/adyen-android/pull/383 😉
