### ISSUE TITLE
Null extracted folder for artifact 2.2.1

### ISSUE THREAD

**Issue by petkaantonov** [Adyen/adyen-3ds2-android#32]
**Describe the bug**

No matter how I try to import 2.2.1 I get this error 

`Null extracted folder for artifact`.

I tried:

`implementation "com.adyen.threeds:adyen-3ds2:2.2.1"`

with both `jcenter()`and `mavenCentral()`as repositories.

I tried 

`implementation "com.adyen.threeds:adyen-3ds2:2.2.1@aar"`

with the aar file in libs folder.

I even tried

`compile files('libs/adyen-3ds2-2.2.1.aar')`

And the error even has correct path:

```
Null extracted folder for artifact: ResolvedArtifact(componentIdentifier=adyen-3ds2-2.2.1.aar, variantName=null, artifactFile=/android/app/libs/adyen-3ds2-2.2.1.aar, extractedFolder=null, dependencyType=ANDROID, isWrappedModule=false, buildMapping={__current_build__=/android}, mavenCoordinatesCache=com.android.build.gradle.internal.ide.dependencies.MavenCoordinatesCacheBuildService$Inject@7908d45)
```

**Desktop (please complete the following information):**
 
Big Sur 11.3.1, android studio 4.2, gradle 4.2

Note that this is issue with 2.2.1, because when I do this, it works:

`implementation "com.adyen.threeds:adyen-3ds2:2.2.0"`

**Comment by caiofaustino** [comment]
Can you test with latest 2.2.2 release please?

**Comment by petkaantonov** [comment]
2.2.2 works
