### ISSUE TITLE
Invalid challengeParameters when trying to do challenge 

### ISSUE THREAD

**Issue by husamk** [Adyen/adyen-3ds2-android#33]
**Describe the bug**
trying to perform a challenge on a test adyen card, but receiving that ChallengeParameters is invalid

val challengeParameters = ChallengeParameters() challengeParameters.set3DSServerTransactionID(threeDSServerTransID) challengeParameters.acsTransactionID = acsTransID challengeParameters.acsRefNumber = acsReferenceNumber challengeParameters.acsSignedContent = acsSignedContent

threeDSServerTransID
33edcbd2-162f-4f98-a345-84574af93c4d

**To Reproduce**
1. submit a credit card number that need 3DS2
2. on performing the challenge the exception is thrown

**Expected behavior**
The challenge must be performed and a new UI to set the number must be shown

**Screenshots**
![111218110-fe437600-85de-11eb-9790-f5ca8a593476](https://user-images.githubusercontent.com/37999237/120316710-60f70480-c2e6-11eb-99e6-5101f0b90266.png)

**Smartphone (please complete the following information):**
 - Device: Several phones (Huwawei, Samsung)
 - OS: Android
 - Version [e.g. 26, 27, 28, 29]

**Additional context**
**Library version:** **2.2.1, 2.2.2**
**Note**: 2.2.0 is free of this bug.
**Stacktrace:**
com.adyen.threeds2.exception.InvalidInputException: Invalid challengeParameters.
at atd.y.a.a(:2)
at com.adyen.threeds2.internal.w.a(:10)
at com.adyen.threeds2.internal.w.doChallenge(:9)
at app.getaway.reactModules.visaCardManager.CardManagerModule.performChallenge(CardManagerModule.kt:85)
at java.lang.reflect.Method.invoke(Native Method)
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
at android.os.Looper.loop(Looper.java:193)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
at java.lang.Thread.run(Thread.java:764)

**Comment by caiofaustino** [comment]
Hi there, does this happen on a Live card or in the Test cards? 
Are you running the app on Debug? If so, the exception cause should give more insight on what's going on.

**Comment by husamk** [comment]
@caiofaustino it happened on a test card provided by adyen:
Mastercard | 5454 5454 5454 5454 | 03/2030 | 737

I run it on debug mode and all that I got is the stacktrace in the description above. nothing more

**Comment by caiofaustino** [comment]
Does it happen every time? Can you share the values of the `ChallengeParameters`?

**Comment by husamk** [comment]
yes, it happened every time.

ChallengeParameters:
3DSServerTransactionID : cafb88ad-bc1e-4659-aa28-95aece67b435
AcsTransactionID : 09c82248-394e-4e29-a428-e5b1e18622cc

I tested both of them and they can be parsed by UUID.fromString(value)

**Comment by salah-ghanim** [comment]
@caiofaustino this broke user onboarding once enabled on production in our app..  any ETA on when you guys will resolve this ?

**Comment by caiofaustino** [comment]
We are looking into this but we can't reproduce it, so if you guys have any more input about your setup.
Does it happen both in TEST and LIVE? Is your app build Debug or Release? Does it have Proguard/R8 enabled? Do you have PSP reference from these requests? Other examples of the ChallengeParameters content would also be nice.

**Comment by wiensmit** [comment]
@caiofaustino i am encountering the same issue while upgrading from 3.8.1 to 4.0.0

I am building in debug mode on TEST without proguard etc.
used test card 6011 1111 1111 1117

the challenge action is the result of a fingerprint

i am parsing the action for `Adyen3DS2Component.handleAction` with `Threeds2ChallengeAction.SERIALIZER.deserialize(action)`
which looks like this:

![Screenshot 2021-07-12 at 15 38 02](https://user-images.githubusercontent.com/6747711/125297078-35285f00-e327-11eb-89a9-89c3d192b96b.png)

resulting in a action like this

![Screenshot 2021-07-12 at 15 39 53](https://user-images.githubusercontent.com/6747711/125297335-70c32900-e327-11eb-8547-3bae6bc941bb.png)

which when passed to  `Adyen3DS2Component.handleAction` returns as an error 

![Screenshot 2021-07-12 at 15 40 45](https://user-images.githubusercontent.com/6747711/125297731-cb5c8500-e327-11eb-9ed5-99e730b7a6b7.png)

**Comment by caiofaustino** [comment]
hey @wiensmit, can you please try using `Action.SERIALIZER.deserialize(action)` to serialize the Action instead? Just want to check something.

**Comment by wiensmit** [comment]
@caiofaustino sure, doing so results in:

![Screenshot 2021-07-12 at 16 06 58](https://user-images.githubusercontent.com/6747711/125301485-5428f000-e32b-11eb-81c1-111b7d042eb2.png)

**Comment by caiofaustino** [comment]
This is so weird, I just can't seem to reproduce the issue. Can either of you share your TEST merchant account.
Maybe sent it to me by email so it's not public here. caio.faustino@adyen.com

**Comment by wiensmit** [comment]
I just send you the information

**Comment by salah-ghanim** [comment]
@caiofaustino it might help to share all environment details here not just code snippet.

since so many components are involved it can be a million thing, for example which adyen API used, which API version, what authentication message version, which client libraries ....

the fact that this issue was a big problem in production makes it a complete blocker to update.

please let me know if @wiensmit details weren't enough, I'm happy to provide a full description of our integration that causes this issue to appear.

-Salah

**Comment by caiofaustino** [comment]
@salah-ghanim it would be very helpful to get your full details as well trying to find the root cause for this issue, my email is open for any information that might be publicly sensitive :)

**Comment by caiofaustino** [comment]
Hi folks, me again. I've been investigating this with a lot of help from @wiensmit (thx you have been awesome) and I have a theory on what might be happening. Does anyone here directly use on their app, or knows about a dependency on their apps that uses Bouncy Castle?

**Comment by komissarovdenis** [comment]
Hey @caiofaustino. We also have a dependency on Bouncy Castle by `com.android.tools.build:gradle:4.1.3` and have the same situation. So, do you have any results from your investigation yet?

**Comment by caiofaustino** [comment]
Yes, it is indeed a conflict inside of Bouncy Castle because of a combination between code obfuscation, duplicated classes and reflection. I made a fix for it and hope to release it soon. 

The fix is to make BC a regular Gradle transitive dependency so you can resolve that yourself.

**Comment by komissarovdenis** [comment]
Thank you @caiofaustino for the info. We will be very waiting for the fix. 
PS now we have thousands of broken sessions a day by this issue.

**Comment by komissarovdenis** [comment]
@caiofaustino BTW how about downgrading your lib's version from `2.2.2` to `2.2.1` or lower? until we got the fix to make sure that it will work for the customers?

**Comment by caiofaustino** [comment]
Yeah that could work as a temporary fix, I think `2.2.0` was the version before any BC changes. 

I hope to make the new release early next week.

**Comment by caiofaustino** [comment]
hey all, I just release `2.2.3` with the change that should fix this issue, could someone try it out and confirm it's now working?

**Comment by komissarovdenis** [comment]
Thank you @caiofaustino I will prep the internal release and will try the fix soon.
Will provide the feedback once tested

**Comment by husamk** [comment]
@komissarovdenis 
The issue has been resolved in the last version 2.2.3
Thank you.

**Comment by husamk** [comment]
Hi Denis.
The issue has been resolved in the last version 2.2.3
Thank you.

**Comment by komissarovdenis** [comment]
Sorry for the delay, but I also confirm that this fix works.
Thank you/
