### ISSUE TITLE
Android 12 support

### ISSUE THREAD

**Issue by komissarovdenis** [Adyen/adyen-3ds2-android#35]
Hey guys! Starting to support Android 12 I faced with an issue when all `activity`, `service`, and `receiver` must have set one more flag into the AndroidManifest file. 

I am talking about `android:exported`. It's necessary to set `true` for `ChallengeActivity` and for `AppUpgradeBroadcastReceiver` .

For now, as a workaround, it's OK to copy from your AndroidManifest or any other 3rd-party lib. all those defined objects into the application's main one. 

For example, how I set it now

``` 
        <activity
            android:name="com.adyen.threeds2.internal.ui.activity.ChallengeActivity"
            android:exported="true"
            android:launchMode="singleTask"
            android:theme="@style/ThreeDS2Theme.Internal"
            android:windowSoftInputMode="stateHidden">

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="${applicationId}"
                    android:scheme="adyen3ds2" />
            </intent-filter>
        </activity>

        <receiver
            android:name="com.adyen.threeds2.internal.AppUpgradeBroadcastReceiver"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED" />
            </intent-filter>
        </receiver>
```

PS without an explicit set of this flag the app won't be installed on any device.

Link to Android 12 migration manual
https://developer.android.com/about/versions/12/behavior-changes-12#exported

**Comment by caiofaustino** [comment]
Thx for bringing this to our attention, we will update this for the next release.

**Comment by giangpham96** [comment]
@caiofaustino is there any estimation when will the next version be out?

**Comment by caiofaustino** [comment]
We have one last thing pending, but shouldn't take too long, sorry but no precise ETA yet.

**Comment by caiofaustino** [comment]
This is released on version `2.2.3`

**Comment by giangpham96** [comment]
hm, I updated the sdk but seems like the flag wasn't added to AppUpgradeBroadcastReceiver
```xml

        <receiver android:name="com.adyen.threeds2.internal.AppUpgradeBroadcastReceiver" >
            <intent-filter>
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED" />
            </intent-filter>
        </receiver>
```

**Comment by caiofaustino** [comment]
Oh you are correct, sorry for missing that, I'll add that for the next version.

**Comment by ilyasdirin** [comment]
@caiofaustino is there a planned date for the release?

**Comment by caiofaustino** [comment]
Yeap, ASAP, probably today or tomorrow.

**Comment by caiofaustino** [comment]
`2.2.4` is out now :)

**Comment by komissarovdenis** [comment]
Now it works well with Android 12. Thank you.
