### ISSUE TITLE
android build failed due to duplicate classes issue

### ISSUE THREAD

**Issue by kalmeshwargurav** [Adyen/adyen-3ds2-android#36]
**Build failed due to duplicate classes found in multiple libraries**
I added one payment library to my gradle file and tried to build project I am getting build failed due to duplicate classes, You can check logcat output below. Can anyone please help me on this.

**Logcat**
[logcat.txt](https://github.com/Adyen/adyen-3ds2-android/files/6930154/logcat.txt)

**Comment by caiofaustino** [comment]
Hey man, looks like Gson is duplicated, but we don't have that dependency on our code. Can you test again which lib did you add and which version you are using please?

**Comment by tkuntubayev** [comment]
Closing the issue as from the logs it doesn't look like that it is related to 3ds2 sdk.

**Comment by Balsa-Pavlicevic** [comment]
Hi, i have same problem. For the context for my app Google told me i should swap my current "com.adyen.threeds:adyen-3ds 2.1.0-rc08" to some newer version which is from 2.2.+ anyways this is transative dependency of "com.adyen.checkout:3ds2:3.7.2", while i try to transfer to "com.adyen.checkout:3ds2:4.9.1" i am getting Duplicate class error while building project 


logs

`Duplicate class com.adyen.checkout.card.BuildConfig found in modules jetified-card-4.9.1-runtime (com.adyen.checkout:card:4.9.1) and jetified-card-base-3.7.2-runtime (com.adyen.checkout:card-base:3.7.2)
Duplicate class com.adyen.checkout.card.CardComponent found in modules jetified-card-4.9.1-runtime (com.adyen.checkout:card:4.9.1) and jetified-card-base-3.7.2-runtime (com.adyen.checkout:card-base:3.7.2)
Duplicate class com.adyen.checkout.card.CardComponentProvider found in modules jetified-card-4.9.1-runtime (com.adyen.checkout:card:4.9.1) and jetified-card-base-3.7.2-runtime (com.adyen.checkout:card-base:3.7.2)
Duplicate class com.adyen.checkout.card.CardComponentState found in modules jetified-card-4.9.1-runtime (com.adyen.checkout:card:4.9.1) and jetified-card-base-3.7.2-runtime (com.adyen.checkout:card-base:3.7.2)
Duplicate class com.adyen.checkout.card.CardConfiguration found in modules jetified-card-4.9.1-runtime (com.adyen.checkout:card:4.9.1) and jetified-card-base-3.7.2-runtime (com.adyen.checkout:card-base:3.7.2)
Duplicate class com.adyen.checkout.card.CardConfiguration$1 found in modules jetified-card-4.9.1-runtime (com.adyen.checkout:card:4.9.1) and jetified-card-base-3.7.2-runtime (com.adyen.checkout:card-base:3.7.2)
Duplicate class com.adyen.checkout.card.CardConfiguration$Builder found in modules jetified-card-4.9.1-runtime (com.adyen.checkout:card:4.9.1) and jetified-card-base-3.7.2-runtime (com.adyen.checkout:card-base:3.7.2)
Duplicate class com.adyen.checkout.card.CardInputData found in modules jetified-card-4.9.1-runtime (com.adyen.checkout:card:4.9.1) and jetified-card-base-3.7.2-runtime (com.adyen.checkout:card-base:3.7.2)
Duplicate class com.adyen.checkout.card.CardListAdapter found in modules jetified-card-4.9.1-runtime (com.adyen.checkout:card:4.9.1) and jetified-card-ui-3.7.2-runtime (com.adyen.checkout:card-ui:3.7.2)
Duplicate class com.adyen.checkout.card.CardListAdapter$ImageViewHolder found in modules jetified-card-4.9.1-runtime (com.adyen.checkout:card:4.9.1) and jetified-card-ui-3.7.2-runtime (com.adyen.checkout:card-ui:3.7.2)
Duplicate class com.adyen.checkout.card.CardOutputData found in modules jetified-card-4.9.1-runtime (com.adyen.checkout:card:4.9.1) and jetified-card-base-3.7.2-runtime (com.adyen.checkout:card-base:3.7.2)
Duplicate class com.adyen.checkout.card.CardView found in modules jetified-card-4.9.1-runtime (com.adyen.checkout:card:4.9.1) and jetified-card-ui-3.7.2-runtime (com.adyen.checkout:card-ui:3.7.2)
Duplicate class com.adyen.checkout.card.data.CardType found in modules jetified-card-4.9.1-runtime (com.adyen.checkout:card:4.9.1) and jetified-card-base-core-3.7.2-runtime (com.adyen.checkout:card-base-core:3.7.2)
Duplicate class com.adyen.checkout.card.data.ExpiryDate found in modules jetified-card-4.9.1-runtime (com.adyen.checkout:card:4.9.1) and jetified-card-base-core-3.7.2-runtime (com.adyen.checkout:card-base-core:3.7.2)
Duplicate class com.adyen.checkout.card.ui.CardNumberInput found in modules jetified-card-4.9.1-runtime (com.adyen.checkout:card:4.9.1) and jetified-card-ui-core-3.7.2-runtime (com.adyen.checkout:card-ui-core:3.7.2)
Duplicate class com.adyen.checkout.card.ui.ExpiryDateInput found in modules jetified-card-4.9.1-runtime (com.adyen.checkout:card:4.9.1) and jetified-card-ui-core-3.7.2-runtime (com.adyen.checkout:card-ui-core:3.7.2)
Duplicate class com.adyen.checkout.card.ui.SecurityCodeInput found in modules jetified-card-4.9.1-runtime (com.adyen.checkout:card:4.9.1) and jetified-card-ui-core-3.7.2-runtime (com.adyen.checkout:card-ui-core:3.7.2)
Duplicate class com.adyen.checkout.core.BuildConfig found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.api.BaseHttpUrlConnectionFactory found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.api.Connection found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.api.Connection$HttpMethod found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.api.ConnectionTask found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.api.Environment found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.api.Environment$1 found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.api.HttpUrlConnectionFactory found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.api.SSLSocketUtil found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.api.TLSSocketFactory found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.api.ThreadManager found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.code.Lint found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.exception.ApiCallException found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.exception.BadModelException found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.exception.CheckoutException found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.exception.ComponentException found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.exception.ModelSerializationException found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.exception.NoConstructorException found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.log.LogUtil found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.log.Logger found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.log.Logger$LogLevel found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.model.JsonUtils found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.model.ModelObject found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.model.ModelObject$Creator found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.model.ModelObject$Serializer found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.model.ModelUtils found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.util.LocaleUtil found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.util.ParcelUtils found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)
Duplicate class com.adyen.checkout.core.util.StringUtil found in modules jetified-checkout-core-4.9.1-runtime (com.adyen.checkout:checkout-core:4.9.1) and jetified-core-v3-3.7.2-runtime (com.adyen.checkout:core-v3:3.7.2)

Go to the documentation to learn how to Fix dependency resolution errors.`

if you could help me i would be so grateful.

**Comment by tkuntubayev** [comment]
@Balsa-Pavlicevic 
Thank you for raising this.

From the provided logs all duplicate conflicts are connected to libraries that are specific to v3. In v4 `com.adyen.checkout:card-base`, `com.adyen.checkout:card-base-core`,  `com.adyen.checkout:card-ui`, `com.adyen.checkout:card-ui-core` and `com.adyen.checkout:core-v3` are no longer needed if you use `com.adyen.checkout:card:4.9.1`. Could you please remove v3 specific libraries from your project and try again?
