### ISSUE TITLE
AdyenConfigParameters.from does not exist

### ISSUE THREAD

**Issue by dogramacigokhan** [Adyen/adyen-3ds2-android#4]
README file and documentation in the website use `AdyenConfigParameters.from()` in their examples. `from` method is not available in the latest version (0.9.6) of the SDK, I'm assuming that it should be replaced with `new AdyenConfigParameters.Builder().build()`.

**Comment by ran-haveshush** [comment]
@dogramacigokhan thanks for the notice.
We are aware of that, the README file will be updated no the next release.

**Comment by ran-haveshush** [comment]
@dogramacigokhan the readme file is up to date now.
