### ISSUE TITLE
ChallengeActivity is not visible with browserstack

### ISSUE THREAD

**Issue by romainlouvet** [Adyen/adyen-3ds2-android#41]
**Describe the bug**
When I try to load com.adyen.threeds2.internal.ui.activity.ChallengeActivity in my browserstack device, nothing appears on the phone screen.
No problem with physical device

**To Reproduce**
Try to pay with payment card 3ds2

**Screenshots**
![Capture d’écran 2022-01-19 à 15 27 51](https://user-images.githubusercontent.com/4262374/150150612-bba50f05-d054-4bcb-92c1-3bd978548669.png)

**Smartphone (please complete the following information):**
 - Device: Samsung S20
 - OS: Android 10
 - Version: 2.2.4

**Comment by caiofaustino** [comment]
Sorry I'm not familiar with Browserstack, does it work when you run it on a regular Android emulator?

**Comment by romainlouvet** [comment]
yes, no problem with emulator

**Comment by tkuntubayev** [comment]
3DS2 SDK protects the Challenge screen from taking screenshots and capturing videos (for security reasons) by using Android secure flags that makes also impossible for BrowserStack to capture this screen as BrowserStack is not real emulator, it just translates the screen of emulator or real device running on cloud platform to browser window.
