### ISSUE TITLE
Dual-Stack Lite IP resolution problem

### ISSUE THREAD

**Issue by mliberato** [Adyen/adyen-3ds2-android#44]
As per DS-Lite RFC (https://www.rfc-editor.org/rfc/rfc6333.txt), devices may use reserved DS-Lite IPs to make use of IP in IP (IPv4-in-IPv6) and Network Address Translation (NAT), to avoid IPv4 Exhaustion.

For some networks using this technique, the SDK is assigning IP's in the IANA defined DS-Lite well-known range (i.e 192.0.0.4) for field "C010" (3DS SDK Device Information specification). 

Because network provider may deliver the same IP for multiple users using this technique, some issuers are blocking our authentication attempts using IP velocity rules affected by this behavior.

I was able to see this behavior with device Google Pixel 4, Android 12.

Besides loopback addresses, you should ignore as well the IANA defined DS-Lite well-known range, 192.0.0.0/29 (192.0.0.0 to 192.0.0.7).

You may have been experiencing this problem globally, and maybe for both platforms (Android/iOS).

Others have gone thru this in the past:
https://github.com/pusherman/react-native-network-info/pull/70/files

**Comment by tkuntubayev** [comment]
Hey, sorry for the delay. Thanks for sharing that!
We added a filtering for DS-Lite reserved IP addresses. It will be available with the next release (scheduled version 2.2.9).
