### ISSUE TITLE
3DS Localisation Support

### ISSUE THREAD

**Issue by williamyyu** [Adyen/adyen-3ds2-android#50]
Hello 👋 

is there any way to localize the 3DS2 challenge content? 
In the below screenshot, I change my device's local to Spanish and only the `Cancel` button on the top-right corner is displayed in Spanish, but the 3DS2 challenge content and the screen title are still in English. 
![image](https://user-images.githubusercontent.com/8210998/221467635-d890c04e-1344-4122-a103-3c8d5b13113b.png)

Is that something we can control or that's controlled by the issuer (i.e. Bank itself)?

Thanks in advance for the help.

**Comment by tkuntubayev** [comment]
Hi @williamyyu 
Thanks for raising this question!

From the SDK there is no option to localize the content of the challenge as the text is coming from Issuer bank's ACS. Depending on your integration type you can specify `shopperLocale` and `browserInfo.language` field (for challenges redirected to browser) in the initial request that will be sent to ACS. If the locale is supported by ACS the challenge content text should be in according language. Here is documentation
[Checkout API](https://docs.adyen.com/api-explorer/Checkout/70/post/payments#request-shopperLocale)
[Classic API](https://docs.adyen.com/api-explorer/Payment/latest/post/authorise#request-shopperLocale)

**Comment by williamyyu** [comment]
Hello @tkuntubayev , 
Thanks for the answer!

I'm using the Adyen Checkout 3DS2 SDK on Android and found that I can set the `shopperLocale` via Adyen3DS2Configuration. However, I have tried a couple of languages but none of them are working (i.e. still in English). 

I was wondering if the `shopperLocale` is working in the Test environment. 
Also, is there any way to find out what the supported languages by ACS are?

Many thanks!

**Comment by tkuntubayev** [comment]
Thanks for clarifying!
Currently `shopperLocale` passed via Adyen3DS2Configuration is not intended to configure 3DS challenge content.
To indicate the locale for issuer bank's ACS it's needed to send `shopperLocale` and `browserInfo.language` with `/payments` request from your backend the same way as it passed for [`/paymentMethods`](https://docs.adyen.com/api-explorer/Checkout/70/post/paymentMethods#request-shopperLocale) request call. If ACS doesn't support the specific locale - the challenge content will be shown in default locale that ACS support.

**Comment by williamyyu** [comment]
Thank you for the clarification! 
I'll chat with our backend and see how it goes.
Closing this issue for now and thanks again for helping.

**Comment by richarda2b-sq** [comment]
Hi @tkuntubayev  we are looking into this from the API (backend) side and have few questions we are hoping you'd be able to help with:

1. Is `browserInfo.language` only required for 3DS1 challenges?
2. [The docs](https://docs.adyen.com/api-explorer/Checkout/70/post/payments#request-shopperLocale) do not specify the usage for `shopperLocale`. Is this field only used for 3DS2 challenges or does it have an effect on the `/payments` request? 

Thanks

**Comment by himanshumattoo** [comment]
Hi @richarda2b-sq 
Thanks for your questions. 

1. `browserInfo.language` is required for 3DS2 as well. 
2. `shopperLocale` would indeed influence 3DS2 challenges as well. It should not have a negative impact on /payments. 

Hope this helps.
