### ISSUE TITLE
Prefetch device fingerprinting keys / directoryServerRootCertificates

### ISSUE THREAD

**Issue by mliberato** [Adyen/adyen-3ds2-android#51]
The flow to prefetch device fingerprinting keys seems to be incompatible with recently released modification (SDK 2.2.12) of AdyenConfigParameters.Builder, as it expects a directoryServerRootCertificates parameter that is not returned by Adyen's classic API "get3dsAvailability".

Is this parameter required for SDK 2.2.12, or it accepts null?

**Comment by tkuntubayev** [comment]
Hi @mliberato,
Thanks for raising this question!

This parameter accepts null. That means that for device fingerprinting keys prefetching you can pass this value as null

**Comment by mliberato** [comment]
Great, thanks. Just remember to update the documentation here:
https://docs.adyen.com/online-payments/classic-integrations/api-integration-ecommerce/3d-secure/native-3ds2/android-sdk-integration#get-the-3d-secure-2-device-fingerprint
