### ISSUE TITLE
Support custom url path for OOB flow

### ISSUE THREAD

**Issue by mikkoville** [Adyen/adyen-3ds2-android#54]
We are having a problem since we want to update our app to use the new OOB flow released in https://github.com/Adyen/adyen-3ds2-android/releases/tag/2.2.12.

In the docs you tell us to implement support for Android app links the following way:
https://docs.adyen.com/online-payments/classic-integrations/api-integration-ecommerce/3d-secure/native-3ds2/android-sdk-integration#handling-android-app-links

It says in the docs:

_"Copy the following code to your app Manifest file. Replace the value of android:host from {[yourapp.com](http://yourapp.com/)} with your web domain name. Do not change any other configuration."_

I have question about the **"Do not change any other configuration"** part.

The problem:
- Using Android app links with https urls to direct user back to our app has a problem if user decides to sets their device to open App link in a browser instead of the supported app. This is possible from Android settings. So if the user has this setting on instead of going back to the ChallengeActivity they will go to a browser that loads https://{[yourapp.com](http://yourapp.com/)}/adyen3ds2". **So in order to make this new flow work for all cases we need to host such page that tells the user go back to the mobile app.**

**My main question is: Can we change the url path to somethin else than "/adyen3ds2" ?**

We are already hosting another generic path in our domain that fits the purpose and would like to use that instead.

I would imagine it is ok since we then just specify our own path in the AndroidManifest like this:

```
<data
                android:host=""{yourapp.com}""
                android:pathPrefix="/our_custom_path"
                android:scheme="https" />
```

And then when we create the `ChallengeParameters` for the sdk we add:

`challengeParameters.setThreeDSRequestorAppURL("https://{yourapp.com}/our_custom_path")`

**Does the above work? or is there some reason in the docs it says: "Do not change any other configuration"**

**NOTE** I did contact Adyen support first and they did tell me I cannot change the url path from` /adyen3ds2`. I felt little bit they did not understand my problem so I decided to create this issue also to get more clarity.

This is blocking us into optiong into the OOB flow if we cannot use a custom path url.

Thanks

**Comment by tkuntubayev** [comment]
Hi @mikkoville 
Thank you for raising the question!

`Can we change the url path to somethin else than "/adyen3ds2" ?`
Yes, it's possible to use your custom path in the same way as shown on your code examples. The only requirement is that the full link with your custom path should generate unique App Link that is only connected with 3DS2 `ChallengeActivity`. `/adyen3ds2` path  is shown on the docs to generate unique App link for `ChallengeActivity`.

Hope this helps!

**Comment by mikkoville** [comment]
@tkuntubayev thanks! I guess it would be good idea to fix the docs then since it is quite confusing since it says:
"Do not change any other configuration"

**Comment by tkuntubayev** [comment]
Docs page was updated recently. Thank you for suggestion!
