### ISSUE TITLE
Version 2.2.14+ adds over 1 MB of app size

### ISSUE THREAD

**Issue by puboe** [Adyen/adyen-3ds2-android#59]
**Is your feature request related to a problem? Please describe.**
A change in proguard rules in `v2.2.14` has increased our app size by over 1 MB since it's now keeping the entire `org.bouncycastle` package.

Rules in `v2.2.13`
```
-keep class com.adyen.threeds2.** { *; }
-keep class atd.** { *; }
-dontwarn atd.**
```

Rules in `v2.2.14+`
```
-keep class com.adyen.threeds2.** { *; }
-keep class atd.** { *; }
-keep class org.bouncycastle.** { *; }
-dontwarn atd.**
-dontwarn org.bouncycastle.**
```

**Describe the solution you'd like**
Provide, if possible, more optimized rules that keep only the required code in `org.bouncycastle` package so the rest can be stripped down by R8.

**Comment by tkuntubayev** [comment]
Hi @puboe,
Thank you for indicating this. Our team will investigate further if we can make the rules more granular without affecting the stability of the SDK. We will let you know once we have a result.

**Comment by tkuntubayev** [comment]
The new 2.2.16 version has been released with updated proguard rules that keep only necessary code coming from transitive dependencies.
