### ISSUE TITLE
Adyen 3DS2 v2.2.10 sdk fails on initialize with device fingerprinting challenge for a subset of Android OS14 devices.

### ISSUE THREAD

**Issue by jamalana89** [Adyen/adyen-3ds2-android#64]
**Describe the bug**
Adyen 3DS2 v2.2.10 SDK fails on device fingerprinting challenge for a subset of Android OS14 devices.

**To Reproduce**
Use an Android 14 Google Pixel 7/6/8 Pro device and when trying to initialize the SDK to get the deviceFingerprinting, the SDK throws an exemption
`java.lang.SecurityException: Settings key: <enabled_input_methods> is only readable to apps with targetSdkVersion lower than or equal to: 33, 	at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:3308), 	at android.provider.Settings$Secure.getStringForUser(Settings.java:6486), 	at android.provider.Settings$Secure.getString(Settings.java:6452), 	at atd.s.f.b(Unknown Source:30), 	at atd.q.a.a(Unknown Source:2), 	at atd.h.b.a(Unknown Source:16), 	at atd.h.b.<init>(Unknown Source:35), 	at atd.h.b.a(Unknown Source:2), 	at com.adyen.threeds2.internal.g.initialize(Unknown Source:46), 	`

**Expected behavior**
Initialize SDK should not throw exemptions for Android OS 14 subset of devices
Adyen 3DS Service can fallback to Redirect SCA Challenge if they can identify the issue beforehand as they have the info of SDK version and Android OS as their request payload.

**Smartphone (please complete the following information):**
 - Device: Pixel 7/6/8 Pro
 - OS: Android OS 14
 - Version  - v2.2.10

**Additional context**
Android 14 Google Pixel 7/6/8

**Comment by tkuntubayev** [comment]
Hi @jamalana89,
Thank you for reporting. v2.2.10 version was built with main support of Android SDK version 33. Please consider upgrade to the v2.2.15 that solves this issue.

**Comment by jamalana89** [comment]
@tkuntubayev  
Updating the SDK resolves the problem. However, we need a solution for older app versions on Android OS 14. We're considering implementing a forced redirectShopper challenge rather than the usual identify/challenge process for shoppers who are currently getting affected. Can you advise if it's possible to enforce a redirect Challenge when interacting with the Adyen Service?

**Comment by tkuntubayev** [comment]
@jamalana89 not sending `sdkVersion` field in `threeDS2RequestData` object during `/authorise` request will enforce RedirectShopper.
