### ISSUE TITLE
Update Kotlin runtime dependencies to 1.9.21/Serialization BOM 1.6.2

### ISSUE THREAD

**Issue by rcgonzalezf** [Adyen/adyen-3ds2-android#65]
**Is your feature request related to a problem? Please describe.**
The current version depends on an older version of Kotlin (1.8.22) and the Serialization BOM (1.5.1) as you can see here:

https://mvnrepository.com/artifact/com.adyen.threeds/adyen-3ds2/2.2.15

That's a runtime dependency, if it's safe for consumers to update their Kotlin version please mention it in a compatibility table, that will help to avoid a runtime issue due to the general Kotlin compiler version. 

**Describe the solution you'd like**
Update Kotlin runtime dependencies to 1.9.21/Serialization BOM 1.6.2, or the latest once this ticket is reviewed.

**Describe alternatives you've considered**
Create a compatibility table if it's safe for consumer to have otherwise potentially incompatible versions of the Kotlin Compiler and the Kotlinx serialization BOM.

**Additional context**
https://github.com/Kotlin/kotlinx.serialization?tab=readme-ov-file#setup

**Comment by tkuntubayev** [comment]
Hi @rcgonzalezf,
Thanks for bringing this to our attention. The update of the specified dependencies is planned with the next release.
Regarding the compatibility table we will look into this, thanks for the suggestion.
