### ISSUE TITLE
Kotlin and Kotlinx classes left unmapped in 2.2.16

### ISSUE THREAD

**Issue by anthonymonori** [Adyen/adyen-3ds2-android#68]
**Describe the bug**
After upgrading from 2.2.15 to 2.2.16, there seems to be some unmapped `kotlin.*` and `kotlinx.*` classes introduced that still seem a bit too broad:

```
kotlin.Pair
kotlin.Unit
kotlin.collections.IndexedValue
kotlin.coroutines.CoroutineContext
kotlin.io.FileWalkDirection
kotlin.ranges.IntRange
kotlin.reflect.KClass
kotlin.reflect.KTypeProjection
kotlin.text.MatchGroup
kotlin.text.MatchResult
kotlinx.coroutines.CancelHandler
kotlinx.coroutines.ThreadContextElement
kotlinx.coroutines.debug.internal.DebugProbesImpl
kotlinx.coroutines.flow.Flow
kotlinx.coroutines.internal.ThreadState
kotlinx.coroutines.selects.SelectInstance
kotlinx.serialization.descriptors.ClassSerialDescriptorBuilder
kotlinx.serialization.descriptors.SerialDescriptor
```

Thanks for better handling the previously broad `org.bouncycastle.*` rule to only keep what is really needed, which seems to be `org.bouncycastle.jcajce.provider.asymmetric.rsa.PSSSignatureSpi` but can we do something to avoid having all these classes to be unmapped? Especially concerned if the `kotlinx.serialization.descriptors` may leave some unnecessary pointers in our codebase unmapped and easier to decrypt.

**To Reproduce**
1. Build with 2.2.15
2. Get the `build/outputs/mapping/flavour/mapping.txt`
3. Build with 2.2.16
4. Get the `build/outputs/mapping/flavour/mapping.txt`
5. Compare and spot the difference

**Expected behavior**
Not to have any unnecessary classes left unmapped

**Additional context**
There might be a few more than the ones listed above, as we already allow listed a few `kotlin.*` and `kotlinx.*` namespaces

**Comment by tkuntubayev** [comment]
Hi @anthonymonori,
Thank you for reaching out and describing the proposal. We will investigate further and let you know if there's something can be done from our side.

**Comment by fdcb** [comment]
Hi @anthonymonori, this issue should be resolved in newest release.
