### ISSUE TITLE
Adyen 3ds  crashes on systems using a 16KB Page size 

### ISSUE THREAD

**Issue by anismarzouk808** [Adyen/adyen-3ds2-android#70]
**Describe the bug**
As described in https://developer.android.com/guide/practices/page-sizes, Android 15 adds support for devices that use a 16KB page size. When running the 3ds2 on one of these devices, the following crash occurs:

`A  Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7c31de3e21d0 in tid 4833 (aa.aaa), pid 4833 (aa.aaa) 2024-08-05 15:18:32.495  5353-5353  DEBUG                   crash_dump64                         A  Cmdline: aa.aaa 2024-08-05 15:18:32.495  5353-5353  DEBUG                   crash_dump64                         A  pid: 4833, tid: 4833, name: aa.aaa >>> aa.aaa<<< 2024-08-05 15:18:32.495  5353-5353  DEBUG                   crash_dump64                         A        #00 pc 00000000000021d0  /data/app/~~MOgqhOZdQnF6fAnuFnM0IQ==/aa.aa-YpRrvBbMQ3Ty5h3JDQ37GA==/base.apk (offset 0x1688000) 2024-08-05 15:18:32.495  5353-5353  DEBUG                   crash_dump64                         A        #01 pc 0000000000002c1c  /data/app/~~MOgqhOZdQnF6fAnuFnM0IQ==/aa.aaa-YpRrvBbMQ3Ty5h3JDQ37GA==/base.apk!libaa867d.so (offset 0x1680000) (JNI_OnLoad+2856) (BuildId: 3dde081546e7b4d2)`

the cause is that the native library libaa867d.so does not support devices that are configured to use a page size of 16 KB

**To Reproduce**
Using emulator with Android 15 configured to use a page size of 16 KB,
When paying using 3ds2 the app crashes

**Solution**
You need to rebuild the app to support devices using 16KB page size , see the link provided above for more details

**Comment by tkuntubayev** [comment]
Hi @anismarzouk808 ,
Thank you for sharing this with us. 

The version of 3DS2 SDK that is fully compatible with Android 15 is planned and we will post an update here once it is released.

**Comment by tkuntubayev** [comment]
Hi @anismarzouk808,
The new 3DS2 SDK version that is fully compatible with Android 15 and 16KB Page size devices has been released.
Please check for all updates [here](https://github.com/Adyen/adyen-3ds2-android/releases/tag/2.2.21).
