### ISSUE TITLE
Secure channel setup failure

### ISSUE THREAD

**Issue by Knight704** [Adyen/adyen-3ds2-android#9]
Hi, I followed all the guides on integrating 3ds2 with classic CSE flow.
IdentifyShopper and sending fingerprint data to adyen was success, but then
transaction.doChallenge call throws SDKRuntimeException with error "Secure channel setup failure".
This is reproduced both on simulator and on real device.

**Comment by timon-langlotz** [comment]
Hi @Knight704,

are you calling `ThreeDS2Service.createTransaction(null, null)`, or are you providing specific parameters?
And could you verify the `acsSignedContent` in `ChallengeParameters`?

Regards,
Timon

**Comment by Knight704** [comment]
Hey @timon-langlotz,
sorry, you are right, I'm blindly put challenge data as keys, into ChallengeParameters.

Everything is fine

**Comment by timon-langlotz** [comment]
Great to hear that it's resolved!
Cheers,
Timon
